name: ◡🥀𝓐𝓸𝓲𝓒𝓱𝓪𝓷🥀◡ xóa

on:
  push:
   branches: ["main"]
  workflow_dispatch:

permissions:
  actions: write
  id-token: write

jobs:
  aoichan:
    name: 🍒𝓐𝓸𝓲𝓒𝓱𝓪𝓷🦋
    runs-on: ubuntu-latest
    
    steps:
      - name: 🗑️ 𝐎𝐋𝐃 deployment
        run: |
          gh api repos/${{ github.repository }}/deployments \
            --jq '.[] | select(.environment=="github-pages") | .id' \
            | while read id; do
                echo "🗑️ deleting deployment $id"
                gh api repos/${{ github.repository }}/deployments/$id -X DELETE
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_WEB }} 
        
      - name: 🗑️ 𝐎𝐋𝐃 𝐖𝐎𝐑𝐊𝐅𝐋𝐎𝐖𝐒
        run: |
          gh api repos/${{ github.repository }}/actions/runs \
            --paginate \
            --jq '.workflow_runs | sort_by(.created_at) | reverse | .[1:] | map(select(.status=="completed")) | .[].id' \
            | while read run; do
                echo "🗑️ đã xóa $run"
                gh api repos/${{ github.repository }}/actions/runs/$run -X DELETE
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_WEB }}

      - name: 🗑️ 𝐎𝐋𝐃 𝐂𝐀𝐂𝐇𝐄
        run: |
          gh cache list --json id,createdAt \
            | jq 'sort_by(.createdAt) | reverse | .[1:] | .[].id' \
            | while read id; do
                echo "🗑️ đã xóa $id"
                gh cache delete "$id"
              done
        env:
          GH_TOKEN: ${{ secrets.AOI_WEB }}
